typography_spectrum: 0.54894
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.25903685740195215
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.7435887199826539
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Brainfreeze Networks
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Brainfreeze Networks
description: This has nothing to do with Slurpees.
purpose: []
